// Storage keys — MMKV (§3.2)
export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'auth.accessToken',
  REFRESH_TOKEN: 'auth.refreshToken',
  USER: 'auth.user',
  COMPANY: 'auth.company',
  THEME: 'app.theme',
  ONBOARDED: 'app.onboarded',
} as const;

// All API endpoints — prefix /api/v1 is set on the Axios base URL (§0, §3.1)
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    SELECT_COMPANY: '/auth/select-company',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    MY_PERMISSIONS: '/auth/my-permissions',
    MY_COMPANIES: '/auth/my-companies',
    SWITCH_COMPANY: '/auth/switch-company',
    FORGOT_PASSWORD: '/auth/forgot-password',
    VALIDATE_RESET: '/auth/validate-reset-token',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    VERIFY_2FA: '/auth/verify-2fa',
    RESEND_2FA: '/auth/resend-2fa',
  },
  USERS: {
    ME: '/users/me',
    UPDATE: (id: string) => `/users/${id}`,
    PROFILE: '/users/me',
    UPDATE_PROFILE: '/users/me/profile',
    AVATAR: '/users/me/avatar',
    PREFERENCES: '/users/me/preferences',
  },
  DASHBOARD: {
    FINANCIAL_OVERVIEW: '/dashboard/financial-overview',
    RECENT_ACTIVITY: '/dashboard/recent-activity',
    CASH_FLOW_OVERVIEW: '/dashboard/cash-flow-overview',
    REVENUE_EXPENSE_TREND: '/dashboard/revenue-expense-trend',
    INVOICE_ANALYTICS: '/dashboard/invoice-analytics',
    TOP_CUSTOMERS: '/dashboard/top-customers',
  },
  INVOICES: {
    LIST: '/invoices',
    DETAIL: (id: string) => `/invoices/${id}`,
    NEXT_NUMBER: '/invoices/next-number',
    SUMMARY: '/invoices/summary',
    STATUSES: '/invoices/statuses',
    SEND: (id: string) => `/invoices/${id}/send`,
    VOID: (id: string) => `/invoices/${id}/void`,
    PAYMENTS: (id: string) => `/invoices/${id}/payments`,
    PDF: (id: string) => `/invoices/${id}/pdf`,
  },
  AUDIT_TRAIL: '/audit-trail',
  ESTIMATES: {
    LIST: '/estimates',
    DETAIL: (id: string) => `/estimates/${id}`,
    SUMMARY: '/estimates/summary',
    STATUSES: '/estimates/statuses',
    SEND: (id: string) => `/estimates/${id}/send`,
    ACCEPT: (id: string) => `/estimates/${id}/accept`,
    REJECT: (id: string) => `/estimates/${id}/reject`,
    CONVERT_TO_INVOICE: (id: string) => `/estimates/${id}/convert-to-invoice`,
  },
  CUSTOMERS: {
    LIST: '/customers',
    DETAIL: (id: string) => `/customers/${id}`,
  },
  EXPENSES: {
    LIST: '/expenses',
    DETAIL: (id: string) => `/expenses/${id}`,
    SUMMARY: '/expenses/summary',
  },
  BILLS: {
    LIST: '/bills',
    DETAIL: (id: string) => `/bills/${id}`,
    SUMMARY: '/bills/summary',
    STATUSES: '/bills/statuses',
    PAYMENTS: (id: string) => `/bills/${id}/payments`,
  },
  VENDORS: {
    LIST: '/vendors',
    DETAIL: (id: string) => `/vendors/${id}`,
  },
  APPROVALS: {
    MY_PENDING: '/approvals/my-pending',
    DASHBOARD: '/approvals/dashboard',
    DETAIL: (id: string) => `/approvals/${id}`,
    ENTITY: (type: string, id: string) => `/approvals/entity/${type}/${id}`,
    APPROVE: (id: string) => `/approvals/${id}/approve`,
    REJECT: (id: string) => `/approvals/${id}/reject`,
  },
  TIME_ENTRIES: {
    LIST: '/time-entries',
    DETAIL: (id: string) => `/time-entries/${id}`,
    SUBMIT: '/time-entries/submit',
  },
  PROJECTS: {
    LIST: '/projects',
    DETAIL: (id: string) => `/projects/${id}`,
    PROFITABILITY: (id: string) => `/projects/${id}/profitability`,
  },
  BANKING: {
    ACCOUNTS: '/banking/accounts',
    TRANSACTIONS: (accountId: string) => `/banking/accounts/${accountId}/transactions`,
    TRANSACTION: (id: string) => `/banking/transactions/${id}`,
    RECONCILIATIONS: (id: string) => `/banking/reconciliations/${id}`,
  },
  REPORTS: {
    PROFIT_LOSS: '/reports/profit-loss',
    BALANCE_SHEET: '/reports/balance-sheet',
    CASH_FLOW: '/reports/cash-flow',
    AR_AGING: '/reports/ar-aging',
    AP_AGING: '/reports/ap-aging',
    SALES_BY_CUSTOMER: '/reports/sales-by-customer',
  },
  PRODUCTS: {
    LIST: '/products',
    DETAIL: (id: string) => `/products/${id}`,
    STOCK_CARD: (id: string) => `/inventory/product/${id}/stock-card`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    READ: (id: string) => `/notifications/${id}/read`,
    PREFERENCES: '/notifications/preferences',
  },
  CURRENCIES: {
    LIST: '/currencies',
    BASE: '/currencies/base',
  },
  ACCOUNTS: '/accounts',
  CATEGORIES: '/categories',
  TAXES: {
    LIST: '/taxes',
    RATES: '/taxes/rates',
  },
  CLASSES: '/classes',
  DEPARTMENTS: '/departments',
} as const;
